//https://www.youtube.com/watch?v=k-Pi5ZMxHWY&ab_channel=developedbyed

import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import Image from "next/image";
import logo from "../public/logo.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className= {darkMode ? "dark" : ""}>
      <Head>
        <title>Micheál Fiachra Mac Cóil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fi.ico" />
        <link href="/dist/output.css" rel="stylesheet"></link>
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">developedbyFi</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/></li>
              <li><a className="bg-gradient-to-b from-slate-200 to-slate-500 text-white px-4 py-2 rounded-md ml-8" href="#">cv</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-4xl py-2">Micheál Fiachra Mac Cóil</h2>
            <h3 className="text-2xl py-2">Web developer and designer</h3>
            <p className="text-md py-5 leading-8">On a journey of designing and developing on the interwebs</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-500">
           <AiFillTwitterCircle />
           <AiFillLinkedin />
           <AiFillYoutube /> 
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-slate-100 rounded-full w-80 h-80 mt-20">
            <Image src={logo} layout="fill" objectFit="cover"/>
          </div>
        </section>

        <section>
          <div className="text-center py-5">
            <h3 className="text-lg font-medium pt-8 pb-2">Services I offer</h3>
            <p className="text-md py-2 leading-8">I love designing and coming up with ideas for projects of all kinds.</p>
          </div>
          <div className="lg:flex gap-10 justify-between">
          <div className="text-center shadow-lg p-10 rounded-xl my-10">
            <Image src={design} width={100} height={100} />
            <h3 className="text-lg font-medium pt-8 pb-2">Design</h3>
            <p className="py-2">Creating beautiful designs to help users do their thing.</p>
            <h4 className="py-4">Design tools I use</h4>
            <p>Photoshop</p>
            <p>Illustrator</p>
            <p>Figma</p>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10">
            <Image src={code} width={100} height={100} />
            <h3 className="text-lg font-medium pt-8 pb-2">Code</h3>
            <p className="py-2">The adventure of learning and implenting code continues.</p>
            <h4 className="py-4">Code languages I speak</h4>
            <p>HTML</p>
            <p>CSS</p>
            <p>Javascript</p>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10">
            <Image src={consulting} width={100} height={100} />
            <h3 className="text-lg font-medium pt-8 pb-2">Teamwork</h3>
            <p className="py-2">Working with other people, to listen, learn and share.</p>
            <h4 className="py-4">Sharing tools I use</h4>
            <p>Github</p>
            <p>Trello</p>
            <p>Codesandbox</p>
          </div>
          </div>
        </section>
        <section>
          <div className="text-center">
            <h3 className="text-lg font-medium pt-8 pb-2">Portfolio</h3>
            <p className="text-md py-2 leading-8">Some examples of my work</p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={"100%"} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={"100%"} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={"100%"} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={"100%"} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={"100%"} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={"100%"} layout="responsive"/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
