import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Micheál Fiachra Mac Cóil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/dist/output.css" rel="stylesheet"></link>
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">developedbyFi</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill className="cursor-pointer text-2xl"/></li>
              <li><a className="bg-gradient-to-b from-slate-200 to-slate-500 text-white px-4 py-2 rounded-md ml-8" href="#">cv</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-4xl py-2">Micheál Fiachra Mac Cóil</h2>
            <h3 className="text-2xl py-2">Web developer and designer</h3>
            <p className="text-md py-5 leading-8">On a journey of designing and developing on the interwebs</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-500">
           <AiFillTwitterCircle />
           <AiFillLinkedin />
           <AiFillYoutube /> 
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3l py-1">Services I offer</h3>
          </div>
        </section>
      </main>
    </div>
  )
}
